# 8.예외처리

## 1.예외처리
### 1.1 프로그램 오류

프로그램이 실행 중 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우.
이러한 결과를 초래하는 원인을 에러 또는 오류라고 한다.

	컴파일 에러 - 컴파일 할 때 발생하는 에러
	런타임 에러 - 프로그램 실행도중에 발생하는 에러

자바에서는 실행 시 발생할 수 있는 프로그램 오류를 '에러'와 '오류' 두가지로 구분

	에러 - 프로그램 코드에 의해서 수습될 수 없는 심각한 문제
    예외 - 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 문제

### 1.2 예외처리의 정의와 목적

	예외처리의
    정의 - 프로그램 실행 시 발생할 수 있는 예외의 발생에 대비한 코드를 작성하는 것
    목적 - 프로그램의 비정상 종료를 막고, 정상적인 실행상태를 유지하는 것

### 1.3 예외처리구문 - try-catch
````java
try{
//예외가 발생할 가능성이 있는 문장들을 넣는다.
}catch(Exception1 e1){
//Exception1이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
}catch(Exception2 e2){
//Exception2가 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
...
}catch(ExceptionN en){
//ExceptionN이 발생했을 경우, 이를 처리하기 위한 문장을 적는다.
}
````

하나의 try블럭 다음에는 여러종류의 예외처리할 수 있도록 하나 이상의 catch블럭이 올수있음.
이 중 발생한 예외의 종류와 일치하는 단 한 개의 catch블럭만 실행.
발생한 예외의 종류와 일치하는 catch블럭이 없으면 예외는 처리되지 않음.

### 1.4 try-catch문에서의 흐름

	-try블럭 내에서 예외가 발생한 경우.
    1.발생한 예외와 일치하는 catch블럭이 있는지 확인한다.
    2.일치하는 catch블럭을 찾게되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch
      문을 빠져나가서 그 다음 문장을 계속해서 수행한다. 만일 일치하는 catch블럭을 찾지 못하면,
      예외는 처리되지 못한다.
    
    -try블럭 내에서 예외가 발생하지 않은 경우
    1.catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.

### 1.5 예외 발생시키기

	1.먼저, 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든 다음
	  Exception e = new Exception("고의로 발생시켰음");
    2.키워드 throw를 이용해서 예외를 발생시킨다.
      throw e

### 1.6 예외 클래스의 계층구조 -349
자바에서는 실행 시 발생할 수 있는 오류를 클래스로 정의
모든 클래스의 조상은 Object클래스 Exception과 Error클래스도 Object클래스의 자손

예외 클래스들은 다음과 같이 두 개의 그룹

	-RuntimeException클래스와 그 자손클래스들
    -Exception클래스와 그 자손클래스들(RuntimeException과 자손들 제외)

RuntimeException클래스들은 주로 프로그래머의 실수에 의해서 발생될 수 있는 예외들로서
자바의 프로그래밍 요소들과 관계가 깊다.

Exceptionz클래스들은 주로 외부의 영향으로 발생할 수 있는 것들로서, 프로그램의 사용자들의 동작에 의해서
발생하는 경우가 많다. 이런 종류의 예외들은 반드시 처리를 해주어야 한다.

	RuntimeException클래스들 - 프로그래머의 실수로 발생하는 예외
    Exception클래스들 -  사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외

RuntimeException클래스들 그룹에 속하는 예외가 발생할 가능성 있는 코드에는 예외처리를 해주지 않아도
컴파일 시에 문제가 되지 않지만, Exception클래스들 그룹에 속하는 예외가 발생할 가능성이 있는 예외는
반드시 처리를 해주어야 하며, 그렇지 않으면 컴파일 시에 에러가 발생한다.

### 1.7 예외의 발생과 catch블럭
catch블럭은 괄호()와 블럭{} 두 부분으로 나눠져 있는데,
괄호()내에는 처리하고자 하는 예외와 같은 타입의 참조변수를 하나 선언해야한다.

첫 번째 catch블럭부터 차례로 내려가면서 catch블럭의 괄호()내에 선언된 참조변수의 종류와
생성된 예외클래스의 인스턴스에 instanceof연산자를 이용해서 검사하게 되는데,
검사 결과가 true인 catch블럭을 만날 때까지 검사는 계속된다.

검사결과가 true인 catch블럭을 찾게되면 블럭에 있는 문장들을 모두 수행한 후에 try-catch문을
빠져나가고 예외처리는 되지만, 검사결과가 true인 catch블럭이 하나도 없으면 예외는 처리되지 않음

모든 예외 클래스는 Exception클래스의 자손이므로, catch블럭의 괄호()에 Exception클래스 타입의
참조변수를 선언해 놓으면 어떤 종류의 예외가 발생하더라도 이 catch문에 의해서 처리된다.

	printStackTrace() - 예외발생 당시의 호출스택에 있었던 메서드의 정보와
    					예외메시지를 화면에 출력한다.
    getMessage() -  발생한 예외클래스의 인스턴스의 인스턴스에 저장된 메시지를 얻을 수 있다.

### 1.8 finally블럭
finally블럭은 try-catch문과 함께 예외 발생여부에 상관없이 실행되어야할 코드를 포함시킬 목적으로 사용
```java
try{
	//예외가 발생할 가능성이 있는 문장들을 넣는다.
}catch(Exception e1){
	//예외처리를 위한 문장을 적는다.
}finally{
    //예외의 발생여부에 관계없이 항상 수행되어야하는 문장을 넣는다.
    //finally블럭은 try-catch문의 맨 마지막에 위치해야한다.
}
```

예외가 발생한 경우 'try-catch-fianally' 순으로 실행,
예외가 발생하지 않는 경우 'try-finally' 순으로 실행
catch블럭의 문장 수행 중에 return문을 만나도 finally블럭의 문장들은 수행된다.

### 1.9 메서드에 예외 선언하기
메서드에 예외를 선언하려면, 에서드의 선언부에 키워드 throws를 사용해서 메서드내에서 발생할 수 있는
예외를 적어주기만 하면 된다. 예외가 여러 개일 경우에는 쉼표(,)로 구분한다.

```java
void method() throws Exception1,Exception1, .... ExceptionN{
	//메서드 내용
}
```

자바에서는 메서드를 작성할 때 메서드 내에서 발생할 가능성이 있는 예외를 메서드의 선언부에
명시하여 이 메서드를 사용하는 쪽에서는 이에 대한 처리를 하도록 강요

[참고] 반드시 처리해주어야 하는 예외는 Exception클래스(RuntimeException클래스들 제외)들이다.

예외를 메서든의 throws에 명시하는 것은 예외를 처리하는 것이 아니라,
자신(예외가 발생할 가능성이 있는 메서드)을 호출한 메서드에게 예외를 전달하여 예외처리를 떠맡기는 것이다.

예외를 전달받은 메서드가 또다시 자신을 호출한 메서드에게 전달할 수 있으며,
이런 식으로 계속 호출스택에 있는 메서드들을 따라 전달되다가 제일 마지막에 있는 main메서드에서도
예외가 처리되지 않으면, main메서드 마저 종료되어 프로그램이 전체가 종료된다.

예외가 발생한 메서드에서 예외처리를 하지 않고, 자신을 호출한 메서드에게 예외를 넘겨줄 수는 있지만,
이것으로 예외가 처리된 것은 아니고 예외를 단순히 전달만 하는 것이다.
어느 한 곳에서는 반드시try-catch문으로 예외처리를 해주어야 한다.

### 1.10 예외 되던지기
한 메서드에서 발생할 수 있는 예외가 여럿인 경우, 몇개는 try-catch문을 통해서 메서든 내에서
자체적으로 처리하고, 그 나머지는 선언부에 지정하여 호출한 메서드에서 처리 하도록 함으로써,
양쪽에서 나눠 처리되도록 할 수 있다.

예외를 처리한 후에 인위적으로 다시 발생시키는 방법을 통해서 가능한데, 이것을 '예외 되던지기'이라고 한다.

하나의 예외에 대해서 예외가 발생한 메서드와 이를 호출한 메서드 양쪽 모두에서 처리해줘야 할 작업이 있을때 사용된다.
주의해야 할 점은 예외가 발생할 메서드에서는 try-catch문을 사용해서 예외처리를 해줌과 동시에 메서등의 서언부에 발생할 예외를 throws에 지정해줘야 한다는 것이다.

### 1.11. 사용자정의 예외 만들기 -367
기존의 정의된 예외 클래스 외에 필요에 따라 프로그래머가 새로운 예외 클래스를 정의하여 사용할 수 있다.
보통 Exception클래스로부터 상속받는 클래스를 만들지만, 필요에 따라서 알맞은 예외 클래스를 선택 할 수있다.









